name: 'Upload release assets'
description: 'Upload all asserts to Release.'
author: 'Nivaes'
inputs:
  upload_url:
    description: 'The URL for uploading assets to the release'
    required: true
  targets:
    description: 'A glob of assets to upload'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
